export type PurchaseGameFamily = {
  id: string
  label: string
  spreadsheetFamily: string
  price: number
}

export const PURCHASE_GAME_FAMILIES: ReadonlyArray<PurchaseGameFamily> = [
  { id: 'family20Strong', label: "20 Strong", spreadsheetFamily: "20 Strong", price: 55.10 },
  { id: 'family7thCitadel', label: "7th Citadel", spreadsheetFamily: "7th Citadel", price: 75.49 },
  { id: 'familyAgemonia', label: "Agemonia", spreadsheetFamily: "Agemonia", price: 130.48 },
  { id: 'arkhamHorrorLcg', label: "Arkham Horror LCG", spreadsheetFamily: "Arkham Horror LCG", price: 921.19 },
  { id: 'familyArydia', label: "Arydia", spreadsheetFamily: "Arydia", price: 179.45 },
  { id: 'familyAssaultOnDoomrockExpansion', label: "Assault on Doomrock + Expansion", spreadsheetFamily: "Assault on Doomrock + Expansion", price: 42.30 },
  { id: 'familyBombBusters', label: "Bomb Busters", spreadsheetFamily: "Bomb Busters", price: 22.94 },
  { id: 'familyBossFightersQR', label: "Boss Fighters QR", spreadsheetFamily: "Boss Fighters QR", price: 28.98 },
  { id: 'bullet', label: "Bullet", spreadsheetFamily: "Bullet", price: 80.37 },
  { id: 'burncycle', label: "burncycle", spreadsheetFamily: "Burncycle", price: 144.22 },
  { id: 'cloudspire', label: "Cloudspire", spreadsheetFamily: "Cloudspire", price: 175.00 },
  { id: 'familyCorpOfDiscovery', label: "Corp of Discovery", spreadsheetFamily: "Corp of Discovery", price: 40.50 },
  { id: 'familyCyberpunkLegends', label: "Cyberpunk Legends", spreadsheetFamily: "Cyberpunk Legends", price: 30.06 },
  { id: 'familyDeadCells', label: "Dead Cells", spreadsheetFamily: "Dead Cells", price: 45.20 },
  { id: 'deathMayDie', label: "Death May Die", spreadsheetFamily: "Cthulu: Death May Die", price: 101.00 },
  { id: 'deckers', label: "Deckers", spreadsheetFamily: "Deckers", price: 34.50 },
  { id: 'familyDiceThrone', label: "Dice Throne", spreadsheetFamily: "Dice Throne", price: 47.06 },
  { id: 'familyDistantSkies', label: "Distant Skies", spreadsheetFamily: "Distant Skies", price: 73.95 },
  { id: 'familyDragonEclipse', label: "Dragon Eclipse", spreadsheetFamily: "Dragon Eclipse", price: 71.79 },
  { id: 'familyDragonholt', label: "Dragonholt", spreadsheetFamily: "Dragonholt", price: 29.49 },
  { id: 'earthborneRangers', label: "Earthborne Rangers", spreadsheetFamily: "Earthborne Rangers", price: 62.00 },
  { id: 'elderScrolls', label: "Elder Scrolls", spreadsheetFamily: "Elder Scrolls Betrayal", price: 379.41 },
  { id: 'familyEtherfield', label: "Etherfield", spreadsheetFamily: "Etherfield", price: 71.65 },
  { id: 'familyEverdellDuo', label: "Everdell Duo", spreadsheetFamily: "Everdell Duo", price: 33.00 },
  { id: 'familyFateforge', label: "Fateforge", spreadsheetFamily: "Fateforge", price: 70.00 },
  { id: 'familyFellowshipTrickTakingGame', label: "Fellowship Trick Taking Game", spreadsheetFamily: "Fellowship Trick Taking Game", price: 20.00 },
  { id: 'finalGirl', label: "Final Girl", spreadsheetFamily: "Final Girl", price: 200.13 },
  { id: 'familyFleshAndBlood', label: "Flesh and Blood", spreadsheetFamily: "Flesh and Blood", price: 15.50 },
  { id: 'familyGloomOfKilforth', label: "Gloom of Kilforth", spreadsheetFamily: "Gloom of Kilforth", price: 24.49 },
  { id: 'familyImperialAssault', label: "Imperial Assault", spreadsheetFamily: "72 Imperial Assault", price: 51.66 },
  { id: 'familyImperium', label: "Imperium", spreadsheetFamily: "Imperium", price: 79.00 },
  { id: 'familyInvincible', label: "Invincible", spreadsheetFamily: "Invincible", price: 31.89 },
  { id: 'isofarianGuard', label: "Isofarian Guard", spreadsheetFamily: "Isofarian Guard", price: 153.00 },
  { id: 'familyKeyforge', label: "Keyforge", spreadsheetFamily: "Keyforge", price: 11.69 },
  { id: 'familyKinfireChronicles', label: "Kinfire Chronicles", spreadsheetFamily: "Kinfire Chronicles", price: 124.99 },
  { id: 'familyKinfireDelve', label: "Kinfire Delve", spreadsheetFamily: "Kinfire Delve", price: 37.99 },
  { id: 'kingdomsForlorn', label: "Kingdoms Forlorn", spreadsheetFamily: "Kingdom Forlorn", price: 365.97 },
  { id: 'familyLeviathanWilds', label: "Leviathan Wilds", spreadsheetFamily: "Leviathan Wilds", price: 89.23 },
  { id: 'mageKnight', label: "Mage Knight", spreadsheetFamily: "Mage Knight", price: 149.95 },
  { id: 'mandalorianAdventures', label: "Mandalorian Adventures", spreadsheetFamily: "Mandalorian Adventures", price: 67.00 },
  { id: 'familyMarvelChampions', label: "Marvel Champions", spreadsheetFamily: "Marvel Champions", price: 84.43 },
  { id: 'familyMind', label: "Mind", spreadsheetFamily: "Mind", price: 0.00 },
  { id: 'mistfall', label: "Mistfall", spreadsheetFamily: "Mistfall", price: 49.63 },
  { id: 'familyMTG', label: "MTG", spreadsheetFamily: "MTG", price: 49.99 },
  { id: 'familyNanolith', label: "Nanolith", spreadsheetFamily: "Nanolith", price: 99.99 },
  { id: 'familyNusfjord', label: "Nusfjord", spreadsheetFamily: "Nusfjord", price: 31.66 },
  { id: 'oathsworn', label: "Oathsworn", spreadsheetFamily: "Oathsworn", price: 119.99 },
  { id: 'familyOnward', label: "Onward", spreadsheetFamily: "Onward", price: 63.91 },
  { id: 'paleo', label: "Paleo", spreadsheetFamily: "Paleo", price: 38.85 },
  { id: 'familyPhantomEpoch', label: "Phantom Epoch", spreadsheetFamily: "Phantom Epoch", price: 135.00 },
  { id: 'familyPuzzleStrike2', label: "Puzzle Strike 2", spreadsheetFamily: "Puzzle Strike 2", price: 44.99 },
  { id: 'familyRadiance', label: "Radiance", spreadsheetFamily: "Radiance", price: 42.38 },
  { id: 'familyRadlands', label: "Radlands", spreadsheetFamily: "Radlands", price: 18.00 },
  { id: 'robinsonCrusoe', label: "Robinson Crusoe", spreadsheetFamily: "Robinson Crusoe", price: 51.78 },
  { id: 'familyRogueAngels', label: "Rogue Angels", spreadsheetFamily: "Rogue Angels", price: 101.00 },
  { id: 'familyRove', label: "Rove", spreadsheetFamily: "Rove", price: 45.08 },
  { id: 'familyScout', label: "Scout", spreadsheetFamily: "Scout", price: 0.00 },
  { id: 'familySeaSaltAndPaper', label: "Sea Salt and Paper", spreadsheetFamily: "Sea Salt and Paper", price: 0.00 },
  { id: 'familySkyTeam', label: "Sky Team", spreadsheetFamily: "Sky Team", price: 16.99 },
  { id: 'skytearHorde', label: "Skytear Horde", spreadsheetFamily: "Skytear Horde", price: 200.00 },
  { id: 'familySleepingGods', label: "Sleeping Gods", spreadsheetFamily: "Sleeping Gods", price: 82.65 },
  { id: 'familySongOfSilveranth', label: "Song of Silveranth", spreadsheetFamily: "Song of Silveranth", price: 126.48 },
  { id: 'starTrekCaptainsChair', label: "Star Trek: Captain's Chair", spreadsheetFamily: "Star Trek Captain's Chair", price: 53.98 },
  { id: 'familySuperPixelTactics', label: "Super Pixel Tactics", spreadsheetFamily: "Super Pixel Tactics", price: 110.86 },
  { id: 'familySwordAndSorcery', label: "Sword and Sorcery", spreadsheetFamily: "Sword and Sorcery", price: 312.95 },
  { id: 'familyTagTeam', label: "Tag Team", spreadsheetFamily: "Tag Team", price: 15.44 },
  { id: 'taintedGrail', label: "Tainted Grail", spreadsheetFamily: "Tainted Grail", price: 99.97 },
  { id: 'familyTalesFromTheRedDragonInn', label: "Tales From the Red Dragon Inn", spreadsheetFamily: "Tales From the Red Dragon Inn", price: 83.99 },
  { id: 'familyTamashii', label: "Tamashii", spreadsheetFamily: "Tamashii", price: 54.96 },
  { id: 'familyTheAnarchy', label: "The Anarchy", spreadsheetFamily: "The Anarchy", price: 49.20 },
  { id: 'familyTidalBlades2', label: "Tidal Blades 2", spreadsheetFamily: "Tidal Blades 2", price: 65.81 },
  { id: 'tooManyBones', label: "Too Many Bones", spreadsheetFamily: "Too Many Bones", price: 330.47 },
  { id: 'undauntedNormandy', label: "Undaunted: Normandy", spreadsheetFamily: "Undaunted", price: 55.50 },
  { id: 'familyUnderFallingSkies', label: "Under Falling Skies", spreadsheetFamily: "Under Falling Skies", price: 21.40 },
  { id: 'unsettled', label: "Unsettled", spreadsheetFamily: "Unsettled", price: 108.03 },
  { id: 'familyUnstoppable', label: "Unstoppable", spreadsheetFamily: "Unstoppable", price: 46.90 },
  { id: 'familyVantage', label: "Vantage", spreadsheetFamily: "Vantage", price: 56.18 },
  { id: 'familyWanderingGalaxy', label: "Wandering Galaxy", spreadsheetFamily: "Wandering Galaxy", price: 40.21 },
  { id: 'familyWarpsEdge', label: "Warps Edge", spreadsheetFamily: "Warps Edge", price: 25.66 },
]

export const purchaseGameFamilyById = new Map(
  PURCHASE_GAME_FAMILIES.map((family) => [family.id, family] as const),
)

export function isPurchaseGameFamilyId(value: string): boolean {
  return purchaseGameFamilyById.has(value)
}
